# 教材

In [2]:
import numpy as np

arr1 = np.array([1,2,3,4])
print('创建的数组: ',arr1)

创建的数组:  [1 2 3 4]


In [13]:
arr2 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(arr2)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [14]:
print(arr2.shape)

(3, 4)


In [15]:
print(arr2.dtype)

int32


In [16]:
print(arr2.size)

12


In [17]:
print(arr2.itemsize)

4


In [19]:
arr2.shape = 4,3 # 转化要求：只能是转置
print(arr2)

[[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  9 10]]


In [20]:
print(np.arange(0,1,0.1)) # 3:step

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [21]:
print(np.linspace(0,1,12)) # 3:len

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


In [23]:
print(np.logspace(0,2,20)) # 3 等比数列，生成10^0~10^0的20个数

[  1.           1.27427499   1.62377674   2.06913808   2.6366509
   3.35981829   4.2813324    5.45559478   6.95192796   8.8586679
  11.28837892  14.38449888  18.32980711  23.35721469  29.76351442
  37.92690191  48.32930239  61.58482111  78.47599704 100.        ]


In [24]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
print(np.eye(3)) # 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
print(np.diag([1,2,3,4]))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [28]:
print(np.ones([5,3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 转换

In [29]:
print(np.float64(42))

42.0


In [30]:
print(np.int(42.0))

42


In [31]:
print(np.bool(42))

True


In [32]:
print(np.bool(0))

False


In [33]:
print(np.float(True))

1.0


In [34]:
print(np.float(False))

0.0


## 创建数据类型

In [39]:
import numpy as np

df = np.dtype([("name",np.str_, 40),("numitems",np.int64),("price",np.float64)])
print("数据类型",df)

数据类型 [('name', '<U40'), ('numitems', '<i8'), ('price', '<f8')]


In [40]:
print('数据类型:',df["name"])

数据类型: <U40


In [42]:
print("数据类型",np.dtype(df["name"]))

数据类型 <U40


In [44]:
itemz = np.array([("tomatoes",42,4.14),("cabbages",13,1.72),],dtype=df)
print("自定义数据类型",itemz)

自定义数据类型 [('tomatoes', 42, 4.14) ('cabbages', 13, 1.72)]


## 随机数

In [46]:
print(np.random.random(10))

[0.15149455 0.772581   0.88510908 0.79410283 0.28561561 0.99934916
 0.44668541 0.7707522  0.35657495 0.20312867]


In [47]:
print(np.random.rand(10,5)) # 均匀分布

[[0.91965755 0.35295069 0.15289197 0.79843212 0.98942413]
 [0.32673878 0.44886331 0.12342228 0.35029163 0.1218425 ]
 [0.2891458  0.65861178 0.23522073 0.54097508 0.96604081]
 [0.75129456 0.87853725 0.23326179 0.09298772 0.97302618]
 [0.35552861 0.09199324 0.57370298 0.91728083 0.19770455]
 [0.7422927  0.73377804 0.86947674 0.26000139 0.24168704]
 [0.03394629 0.93842932 0.59621624 0.49721412 0.42934859]
 [0.59304346 0.73584079 0.90830632 0.98040641 0.14837791]
 [0.07202294 0.04493474 0.43121394 0.49635446 0.70719974]
 [0.51262521 0.46144794 0.47626685 0.82965899 0.00914501]]


In [48]:
print(np.random.randn(10,5)) # 正态分布

[[-0.68116137  0.23022367 -0.31574724 -0.14638296  1.01019843]
 [-1.49607061  0.18203933  0.60599523 -0.06315051  2.3169203 ]
 [ 0.47864137  1.02219604 -1.06015121 -1.18847868  0.67939459]
 [ 0.02951529 -0.07690696  0.40574486 -1.09021014  0.04855679]
 [-0.43674165  0.73713059  1.58200734  0.86791729  1.19658316]
 [-0.45495156 -0.44996379  0.5638826   0.70930802 -0.11027095]
 [-1.21257126 -0.06388085 -0.2701595   0.38400223 -1.32683128]
 [-0.16599428 -0.19914224  0.79685677  1.42330375 -0.37647984]
 [-0.47569538  0.3265798   0.53619856 -1.10795343  0.86545133]
 [-0.67300754 -0.60862649  1.75243817 -0.91620602 -0.49615838]]


In [49]:
print(np.random.randint(2,10,size=[2,5]))

[[3 9 7 2 5]
 [6 6 8 7 5]]


## 索引访问

In [50]:
arr = np.arange(10)
print(arr[5])

5


In [51]:
print(arr[3:5])

[3 4]


In [52]:
print(arr[:5])

[0 1 2 3 4]


In [53]:
print(arr[-1])

9


In [55]:
print(arr[2:4])

[2 3]


In [56]:
print(arr[1:-1:2]) # 3:step

[1 3 5 7]


In [58]:
print(arr[5:1:-2]) # 倒叙

[5 3]


### 多维数组

In [59]:
arr = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print(arr)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]


In [60]:
print(arr[0,3:5])

[4 5]


In [61]:
print(arr[1:,2:])

[[ 6  7  8]
 [ 9 10 11]]


In [63]:
print(arr[:,2:])

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [65]:
print(arr[[(0,1,2),(1,2,3)]]) # a->b的映射构成的有序对

[ 2  6 10]


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


In [66]:
print(arr[1:,(0,2,3)])

[[ 4  6  7]
 [ 7  9 10]]


In [67]:
mask = np.array([1,0,1],dtype=np.bool)
print(arr[mask,2])

[3 9]


In [69]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [71]:
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [72]:
print(arr.reshape(3,4).ndim)

2


In [73]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [76]:
print(arr.ravel()) # 展开

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [81]:
print(arr)
print(arr.flatten()) # 横向展开
print(arr.flatten('F')) # 纵向展开

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  8  1  5  9  2  6 10  3  7 11]


## hstack实现横向组合

In [85]:
arr1 = np.arange(12).reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [87]:
arr2 = arr1*2
print(arr2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [88]:
print(np.hstack((arr1,arr2)))

[[ 0  1  2  3  0  2  4  6]
 [ 4  5  6  7  8 10 12 14]
 [ 8  9 10 11 16 18 20 22]]


## vstack 纵向组合

In [89]:
print(np.vstack((arr1,arr2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


## concatenate组合数组

In [94]:
print(np.concatenate((arr1,arr2),axis=1)) # 横向

[[ 0  1  2  3  0  2  4  6]
 [ 4  5  6  7  8 10 12 14]
 [ 8  9 10 11 16 18 20 22]]


In [95]:
print(np.concatenate((arr1,arr2),axis=0)) # 纵向

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


## vsplit 纵向分割

In [97]:
arr = np.arange(16).reshape(4,4)
print(np.vsplit(arr,2))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


## split分割数组

In [98]:
print("横向分割",np.split(arr,2,axis=1))

横向分割 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [99]:
print(np.split(arr,2,axis=0))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


## 创建矩阵

In [100]:
import numpy as np
matr1 = np.mat("1 2 3;4 5 6;7 8 9")
print(matr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [102]:
matr2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(matr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [104]:
arr1 = np.eye(3)
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [108]:
arr1 = np.eye(3)
arr2 = 3*arr1
print(arr2)

[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


In [109]:
print(np.bmat("arr1 arr2; arr1 arr2"))

[[1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]
 [1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]]
