In [2]:
import numpy as np

matr1 = np.mat("1 2 3;4 5 6;7 8 9")
print(matr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
matr2 = matr1*3
print(matr2)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [4]:
print(matr1+matr2)

[[ 4  8 12]
 [16 20 24]
 [28 32 36]]


In [5]:
print(matr1-matr2)

[[ -2  -4  -6]
 [ -8 -10 -12]
 [-14 -16 -18]]


In [8]:
print(np.multiply(matr1,matr2)) # 对应相乘的结果

[[  3  12  27]
 [ 48  75 108]
 [147 192 243]]


In [9]:
print(matr1*matr2) # 矩阵相乘

[[ 90 108 126]
 [198 243 288]
 [306 378 450]]


In [10]:
print(matr1.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [11]:
print(matr1.H)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
print(matr1.I) # 逆矩阵

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [15]:
print(matr1.A) # 返回视图

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## ufunc函数

In [16]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)

[5 7 9]


In [17]:
print(x-y)

[-3 -3 -3]


In [18]:
print(x*y)

[ 4 10 18]


In [19]:
print(x/y)

[0.25 0.4  0.5 ]


In [20]:
print(x**y)

[  1  32 729]


In [21]:
x = np.array([1,3,5])
y = np.array([2,3,4])
print(x<y)

[ True False False]


In [22]:
print(x>y)

[False False  True]


In [23]:
print(x==y)

[False  True False]


In [24]:
print(x>=y)

[False  True  True]


In [25]:
print(x<=y)

[ True  True False]


In [26]:
print(x!=y)

[ True False  True]


In [28]:
print(np.all(x==y)) # 所有都满足才是true

False


In [30]:
print(np.any(x==y)) # 一个满足即可

True


## 数组广播

In [31]:
arr1 = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
print(arr1)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]


In [32]:
print(arr1.shape)

(4, 3)


In [33]:
arr2 = np.array([1,2,3])
print(arr2)

[1 2 3]


In [34]:
print(arr2.shape)

(3,)


In [35]:
print(arr1+arr2)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


理解：一维数组被广播到二维数组上面去

In [36]:
arr1 = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
print(arr1)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]


In [38]:
print(arr1.shape)

(4, 3)


In [40]:
arr2 = np.array([1,2,3,4]).reshape((4,1))
print(arr2)

[[1]
 [2]
 [3]
 [4]]


In [41]:
print(arr2.shape)

(4, 1)


In [42]:
print(arr1+arr2)

[[1 1 1]
 [3 3 3]
 [5 5 5]
 [7 7 7]]


## 统计计算

In [61]:
import numpy as np

arr = np.arange(100).reshape(10,10)
np.save("./save_arr_第二章练习",arr)
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [84]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.arange(0,1.0,0.1)
np.savez("./save_arr2_第二章练习",arr1,arr2) # 保存多个数组，savez, 后缀名改为npz
print(arr1)

[[1 2 3]
 [4 5 6]]


In [85]:
print(arr2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


### 读取

In [86]:
loaded_data = np.load("./save_arr_第二章练习.npy")
print(loaded_data)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [89]:
# 读取含有多个数组的文件
loaded_data1 = np.load("./save_arr2_第二章练习.npz")
type(loaded_data1)
print(loaded_data1['arr_0'])

[[1 2 3]
 [4 5 6]]


In [90]:
arr = np.arange(0,12,0.5).reshape(4,-1)
print(arr)

[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]


In [92]:
# fmt = "%d" 表示保存为整数
np.savetxt("./arr.txt",arr,fmt="%d",delimiter=",")
loaded_data = np.loadtxt("./arr.txt",delimiter=",")
print(loaded_data)

[[ 0.  0.  1.  1.  2.  2.]
 [ 3.  3.  4.  4.  5.  5.]
 [ 6.  6.  7.  7.  8.  8.]
 [ 9.  9. 10. 10. 11. 11.]]


## 统计分析

In [94]:
np.random.seed(42)
arr = np.random.randint(1,10,size=10)
print(arr)

[7 4 8 5 7 3 7 8 5 4]


In [95]:
arr.sort()
print(arr)

[3 4 4 5 5 7 7 7 8 8]


In [96]:
arr = np.random.randint(1,10,size=(3,3))
print(arr)

[[8 8 3]
 [6 5 2]
 [8 6 2]]


In [97]:
arr.sort(axis=1)
print(arr)

[[3 8 8]
 [2 5 6]
 [2 6 8]]


In [98]:
arr.sort(axis=0)
print(arr)

[[2 5 6]
 [2 6 8]
 [3 8 8]]


## argsort

In [99]:
arr = np.array([2,3,6,8,0,7])
print(arr)

[2 3 6 8 0 7]


In [100]:
print(arr.argsort())

[4 0 1 2 5 3]


In [102]:
a = np.array([3,2,6,4,5])
b = np.array([50,30,40,20,10])
c = np.array([400,300,600,100,200])
d = np.lexsort((a,b,c))
print(list(zip(a[d],b[d],c[d])))

[(4, 20, 100), (5, 10, 200), (2, 30, 300), (3, 50, 400), (6, 40, 600)]


## 去重

In [103]:
names = np.array(['a','c','d','c'])
print(names)

['a' 'c' 'd' 'c']


In [104]:
print(np.unique(names))

['a' 'c' 'd']


In [106]:
print(sorted(set(names)))

['a', 'c', 'd']


In [107]:
ints = np.array([1,2,3,4,4,5,6,6,7,8,8,9,10])
print(ints)

[ 1  2  3  4  4  5  6  6  7  8  8  9 10]


In [108]:
print(np.unique(ints))

[ 1  2  3  4  5  6  7  8  9 10]


## 实现重复

In [110]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [111]:
print(np.tile(arr,3))

[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [112]:
np.random.seed(42)
arr = np.random.randint(0,10,size=(3,3))
print(arr)

[[6 3 7]
 [4 6 9]
 [2 6 7]]


In [113]:
print(arr.repeat(2,axis=0))

[[6 3 7]
 [6 3 7]
 [4 6 9]
 [4 6 9]
 [2 6 7]
 [2 6 7]]


In [114]:
print(arr.repeat(2,axis=1))

[[6 6 3 3 7 7]
 [4 4 6 6 9 9]
 [2 2 6 6 7 7]]


In [118]:
import numpy as np

arr = np.arange(20).reshape(4,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [119]:
print(np.sum(arr))

190


In [120]:
print(arr.sum(axis=0)) # 沿着纵轴求和

[30 34 38 42 46]


In [121]:
print(arr.sum(axis=1))

[10 35 60 85]


In [122]:
print(np.mean(arr))

9.5


In [124]:
print(arr.mean(axis=0)) # 沿着纵轴计算数组均值

[ 7.5  8.5  9.5 10.5 11.5]


In [125]:
print(arr.mean(axis=1))

[ 2.  7. 12. 17.]


In [126]:
print(np.std(arr)) # 数组标准差

5.766281297335398


In [127]:
print(np.var(arr))  # 数组方差

33.25


In [128]:
print(np.min(arr)) # 最小值

0


In [129]:
print(np.max(arr))

19


In [133]:
print(np.argmin(arr)) # 返回最小元素的索引
print(np.argmax(arr)) # 返回最大元素的索引

0
19


In [134]:
arr = np.arange(2,10)
print(arr)

[2 3 4 5 6 7 8 9]


In [136]:
print(np.cumsum(arr)) # 各种元素的累计和

[ 2  5  9 14 20 27 35 44]


In [138]:
print(np.cumprod(arr)) # 各个元素的累计积

[     2      6     24    120    720   5040  40320 362880]


# 任务实现

In [139]:
iris_seqal_length = np.loadtxt("./iris_sepal_length.csv",
                              delimiter=",")
print("长度",iris_seqal_length)

长度 [5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


In [141]:
# 排序
iris_seqal_length.sort()
print("排序以后",iris_seqal_length)

排序以后 [4.3 4.4 4.4 4.4 4.5 4.6 4.6 4.6 4.6 4.7 4.7 4.8 4.8 4.8 4.8 4.8 4.9 4.9
 4.9 4.9 4.9 4.9 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.1 5.1 5.1 5.1
 5.1 5.1 5.1 5.1 5.1 5.2 5.2 5.2 5.2 5.3 5.4 5.4 5.4 5.4 5.4 5.4 5.5 5.5
 5.5 5.5 5.5 5.5 5.5 5.6 5.6 5.6 5.6 5.6 5.6 5.7 5.7 5.7 5.7 5.7 5.7 5.7
 5.7 5.8 5.8 5.8 5.8 5.8 5.8 5.8 5.9 5.9 5.9 6.  6.  6.  6.  6.  6.  6.1
 6.1 6.1 6.1 6.1 6.1 6.2 6.2 6.2 6.2 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3
 6.4 6.4 6.4 6.4 6.4 6.4 6.4 6.5 6.5 6.5 6.5 6.5 6.6 6.6 6.7 6.7 6.7 6.7
 6.7 6.7 6.7 6.7 6.8 6.8 6.8 6.9 6.9 6.9 6.9 7.  7.1 7.2 7.2 7.2 7.3 7.4
 7.6 7.7 7.7 7.7 7.7 7.9]


In [142]:
# 去重
print(np.unique(iris_seqal_length))

[4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.
 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6 7.7 7.9]


In [143]:
# 所有元素累计和
print(np.sum(iris_seqal_length))

876.5


In [144]:
# 所有元素累计和
print(np.cumsum(iris_seqal_length))

[  4.3   8.7  13.1  17.5  22.   26.6  31.2  35.8  40.4  45.1  49.8  54.6
  59.4  64.2  69.   73.8  78.7  83.6  88.5  93.4  98.3 103.2 108.2 113.2
 118.2 123.2 128.2 133.2 138.2 143.2 148.2 153.2 158.3 163.4 168.5 173.6
 178.7 183.8 188.9 194.  199.1 204.3 209.5 214.7 219.9 225.2 230.6 236.
 241.4 246.8 252.2 257.6 263.1 268.6 274.1 279.6 285.1 290.6 296.1 301.7
 307.3 312.9 318.5 324.1 329.7 335.4 341.1 346.8 352.5 358.2 363.9 369.6
 375.3 381.1 386.9 392.7 398.5 404.3 410.1 415.9 421.8 427.7 433.6 439.6
 445.6 451.6 457.6 463.6 469.6 475.7 481.8 487.9 494.  500.1 506.2 512.4
 518.6 524.8 531.  537.3 543.6 549.9 556.2 562.5 568.8 575.1 581.4 587.7
 594.1 600.5 606.9 613.3 619.7 626.1 632.5 639.  645.5 652.  658.5 665.
 671.6 678.2 684.9 691.6 698.3 705.  711.7 718.4 725.1 731.8 738.6 745.4
 752.2 759.1 766.  772.9 779.8 786.8 793.9 801.1 808.3 815.5 822.8 830.2
 837.8 845.5 853.2 860.9 868.6 876.5]


In [145]:
# 均值
print(np.mean(iris_seqal_length))

5.843333333333334


In [146]:
# 方差
print(np.var(iris_seqal_length))

0.6811222222222223


In [168]:
# 标准差
print(np.std(iris_seqal_length))

0.8253012917851409


In [148]:
# 最大值
print(np.max(iris_seqal_length))

7.9


In [150]:
print(np.min(iris_seqal_length))

4.3


# 实训

In [152]:
import numpy as np

arr1 = np.arange(0,1,0.01)
print(arr1)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]


In [159]:
arr2 = np.random.randn(100)
print(arr2)

[-0.87030495 -0.50664322 -1.30995069  2.94366342 -1.0962658   0.91488432
 -0.66606062 -0.51378749  0.3013228  -1.45851692 -0.66273831 -0.14647281
 -0.84601702 -0.82248937  1.08672702  1.00498688 -0.44176602 -0.08416509
  1.23701607 -1.42647888  0.33802266  1.9745712   1.96503476 -1.93991122
 -0.76262696  0.16865939 -1.32187695 -0.6682467  -0.137291    1.40132156
 -0.04540266  0.21693673  0.51242373  0.54348869  0.02809946 -1.19708706
  0.7896728   0.43148946 -1.0967523  -0.68230156  0.88751161  0.60548313
 -0.72029799 -0.26993377 -0.14346223  0.61700378  1.2489407   0.06564916
  1.16920765  0.87331697  0.20565013 -1.44348335 -1.02771086  0.74124064
 -1.71052958  0.11897849  1.00048561  0.15242086 -0.60139725 -0.84661436
  0.81615272  0.47170729 -0.2854893   1.06529247  0.85399779  1.78859386
  0.56689407 -0.16450043 -0.14299093 -1.9345702   0.15065904 -0.01571494
 -1.33007407 -0.02528763  1.34316821 -0.73454765 -0.95989463  1.10492822
  0.6342403   3.06109521 -1.31857016  0.72038724  0

四则运算

In [160]:
print(arr1+arr2)

[-0.87030495 -0.49664322 -1.28995069  2.97366342 -1.0562658   0.96488432
 -0.60606062 -0.44378749  0.3813228  -1.36851692 -0.56273831 -0.03647281
 -0.72601702 -0.69248937  1.22672702  1.15498688 -0.28176602  0.08583491
  1.41701607 -1.23647888  0.53802266  2.1845712   2.18503476 -1.70991122
 -0.52262696  0.41865939 -1.06187695 -0.3982467   0.142709    1.69132156
  0.25459734  0.52693673  0.83242373  0.87348869  0.36809946 -0.84708706
  1.1496728   0.80148946 -0.7167523  -0.29230156  1.28751161  1.01548313
 -0.30029799  0.16006623  0.29653777  1.06700378  1.7089407   0.53564916
  1.64920765  1.36331697  0.70565013 -0.93348335 -0.50771086  1.27124064
 -1.17052958  0.66897849  1.56048561  0.72242086 -0.02139725 -0.25661436
  1.41615272  1.08170729  0.3345107   1.69529247  1.49399779  2.43859386
  1.22689407  0.50549957  0.53700907 -1.2445702   0.85065904  0.69428506
 -0.61007407  0.70471237  2.08316821  0.01545235 -0.19989463  1.87492822
  1.4142403   3.85109521 -0.51857016  1.53038724  1

In [161]:
print(arr1-arr2)

[ 0.87030495  0.51664322  1.32995069 -2.91366342  1.1362658  -0.86488432
  0.72606062  0.58378749 -0.2213228   1.54851692  0.76273831  0.25647281
  0.96601702  0.95248937 -0.94672702 -0.85498688  0.60176602  0.25416509
 -1.05701607  1.61647888 -0.13802266 -1.7645712  -1.74503476  2.16991122
  1.00262696  0.08134061  1.58187695  0.9382467   0.417291   -1.11132156
  0.34540266  0.09306327 -0.19242373 -0.21348869  0.31190054  1.54708706
 -0.4296728  -0.06148946  1.4767523   1.07230156 -0.48751161 -0.19548313
  1.14029799  0.69993377  0.58346223 -0.16700378 -0.7889407   0.40435084
 -0.68920765 -0.38331697  0.29434987  1.95348335  1.54771086 -0.21124064
  2.25052958  0.43102151 -0.44048561  0.41757914  1.18139725  1.43661436
 -0.21615272  0.13829271  0.9054893  -0.43529247 -0.21399779 -1.13859386
  0.09310593  0.83450043  0.82299093  2.6245702   0.54934096  0.72571494
  2.05007407  0.75528763 -0.60316821  1.48454765  1.71989463 -0.33492822
  0.1457597  -2.27109521  2.11857016  0.08961276  0

In [162]:
print(arr1*arr2)

[-0.         -0.00506643 -0.02619901  0.0883099  -0.04385063  0.04574422
 -0.03996364 -0.03596512  0.02410582 -0.13126652 -0.06627383 -0.01611201
 -0.10152204 -0.10692362  0.15214178  0.15074803 -0.07068256 -0.01430806
  0.22266289 -0.27103099  0.06760453  0.41465995  0.43230765 -0.44617958
 -0.18303047  0.04216485 -0.34368801 -0.18042661 -0.03844148  0.40638325
 -0.0136208   0.06725039  0.16397559  0.17935127  0.00955382 -0.41898047
  0.28428221  0.1596511  -0.41676587 -0.26609761  0.35500465  0.24824808
 -0.30252516 -0.11607152 -0.06312338  0.2776517   0.57451272  0.0308551
  0.56121967  0.42792531  0.10282507 -0.73617651 -0.53440965  0.39285754
 -0.92368597  0.06543817  0.56027194  0.08687989 -0.3488104  -0.49950247
  0.48969163  0.28774145 -0.17700337  0.67113426  0.54655858  1.16258601
  0.37415009 -0.11021529 -0.09723384 -1.33485343  0.10546133 -0.01115761
 -0.95765333 -0.01845997  0.99394448 -0.55091074 -0.72951992  0.85079473
  0.49470743  2.41826522 -1.05485613  0.58351367  0.

In [163]:
print(arr1/arr2)

[-0.00000000e+00 -1.97377555e-02 -1.52677503e-02  1.01913826e-02
 -3.64875016e-02  5.46517180e-02 -9.00818907e-02 -1.36243099e-01
  2.65496005e-01 -6.17065176e-02 -1.50889119e-01 -7.50992641e-01
 -1.41841119e-01 -1.58056754e-01  1.28827200e-01  1.49255680e-01
 -3.62182675e-01 -2.01983993e+00  1.45511448e-01 -1.33195102e-01
  5.91676311e-01  1.06352205e-01  1.11957307e-01 -1.18562127e-01
 -3.14701697e-01  1.48227741e+00 -1.96690017e-01 -4.04042400e-01
 -2.03946357e+00  2.06947504e-01 -6.60754306e+00  1.42898810e+00
  6.24483176e-01  6.07188347e-01  1.20998752e+01 -2.92376395e-01
  4.55885017e-01  8.57494867e-01 -3.46477505e-01 -5.71594762e-01
  4.50698327e-01  6.77145207e-01 -5.83092004e-01 -1.59298335e+00
 -3.06700935e+00  7.29331031e-01  3.68312123e-01  7.15926927e+00
  4.10534434e-01  5.61079216e-01  2.43131376e+00 -3.53312007e-01
 -5.05978888e-01  7.15017465e-01 -3.15691706e-01  4.62268425e+00
  5.59728192e-01  3.73964555e+00 -9.64420779e-01 -6.96893450e-01
  7.35156525e-01  1.29317

In [170]:
print("最大值",np.max(arr2))
print("最小值",np.min(arr2))
print("平均值",np.mean(arr2))
print("方差",np.std(arr2))
print("标准差",np.var(arr2))

最大值 3.06109521437826
最小值 -1.9442295937495997
平均值 0.067340096554519
方差 1.0449116390258357
标准差 1.0918403333716586


2

In [180]:
import numpy as np
arr1 = np.eye(2)
print(np.bmat("arr1 arr1 arr1 arr1; arr1 arr1 arr1 arr1;arr1 arr1 arr1 arr1; arr1 arr1 arr1 arr1"))

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
